name: mychatapp
description: "My own take of a chat app"
publish_to: 'none'
version: 0.0.8

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser:
  image_picker: ^1.0.7
  pocketbase: ^0.18.1
  flutter_riverpod: ^2.4.9
  google_mobile_ads: ^5.0.0
  shared_preferences: ^2.2.2
  feedback: ^3.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  firebase_core: ^2.26.0
  firebase_analytics: ^10.8.8
  firebase_messaging: ^14.7.19
  firebase_crashlytics: ^3.4.17
  firebase_performance: ^0.9.3+16
  firebase_remote_config: ^4.3.16
  google_mlkit_smart_reply: ^0.9.0
  fetch_client: ^1.1.0-wasm
  timeago: ^3.6.1
  locale_emoji: ^0.2.1
  google_generative_ai: ^0.2.2
  flutter_markdown: any
  flutter_launcher_icons: ^0.13.1
  flutter_image_compress: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
