name: mychatapp
description: "My own take of a chat app"
publish_to: 'none'
version: 0.0.27

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser:
  image_picker: ^1.0.7
  pocketbase: ^0.22.0
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  feedback: ^3.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  firebase_core: ^3.1.0
  firebase_analytics: ^11.0.1
  firebase_messaging: ^15.0.1
  firebase_crashlytics: ^4.0.1
  firebase_performance: ^0.10.0+1
  firebase_remote_config: ^5.0.1
  google_mlkit_smart_reply: ^0.13.0
  fetch_client: ^1.1.0-wasm
  timeago: ^3.7.0
  locale_emoji: ^1.0.0
  google_generative_ai: ^0.4.0
  flutter_markdown: any
  image: ^4.1.7
  google_mobile_ads: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  generate: true
  uses-material-design: true
