// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASdynnEYFW2BE31s_h-6nZCd1lASFIc6U',
    appId: '1:999227741912:web:1cdc325da355e2260269ad',
    messagingSenderId: '999227741912',
    projectId: 'mychatapp-lg',
    authDomain: 'mychatapp-lg.firebaseapp.com',
    storageBucket: 'mychatapp-lg.appspot.com',
    measurementId: 'G-KFZ03MM9R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNcCkMgxmt6tjamq8L-8E0L1mkc0bRUGk',
    appId: '1:999227741912:android:78ad6b536261ec310269ad',
    messagingSenderId: '999227741912',
    projectId: 'mychatapp-lg',
    storageBucket: 'mychatapp-lg.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASdynnEYFW2BE31s_h-6nZCd1lASFIc6U',
    appId: '1:999227741912:web:0c2acdf901ce73aa0269ad',
    messagingSenderId: '999227741912',
    projectId: 'mychatapp-lg',
    authDomain: 'mychatapp-lg.firebaseapp.com',
    storageBucket: 'mychatapp-lg.appspot.com',
    measurementId: 'G-J4V17W7Z1X',
  );
}
